// <auto-generated />
using EulerProblems.Lib.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lib.Migrations
{
    [DbContext(typeof(EulerContext))]
    partial class EulerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EulerProblems.Lib.DAL.Models.Baseline", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("averageDuration")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("averagedurationms");

                    b.Property<string>("percentile90Duration")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("percentile90durationms");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.ToTable("baseline");
                });

            modelBuilder.Entity("EulerProblems.Lib.DAL.Models.Problem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("solution")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("solution");

                    b.HasKey("id");

                    b.HasIndex("id");

                    b.ToTable("problem");
                });
#pragma warning restore 612, 618
        }
    }
}
